Fix ExecStop command in nbd@.service.sh.in
Passing the device path results in an error:

```
nbd-client -d /dev/nbd0 
Error: Invalid nbd device target

Exiting.
```

Therefore, don't pass the full device path, which is also consistent with how `ExecStart` uses `nbd-client`.