nbd: fix build failure after openunix/opennet refactor
Commit 17043b068f43 ("Refactor the negotiate() and connected functions")
removed all parameters from openunix() and opennet(), but main()
still called them with host/port arguments. This causes build errors:

nbd-client.c:1224:32: error: too many arguments to function ‘openunix’; expected 0, have 1
nbd-client.c:1226:32: error: too many arguments to function ‘opennet’; expected 0, have 2

Update the calls in main() to match the new prototypes.

Fixes: 17043b068f43 ("Refactor the negotiate() and connected functions")
Signed-off-by: Yunseong Kim <ysk@kzalloc.com>
Signed-off-by: Wouter Verhelst <w@uter.be>